schema_version: 7.0
type: producer
identifier: lv2
title: LV2
version: 1
license: GPLv2
language: en
tags:
  - Audio
description: Generate audio using LV2 plugins.
notes: >
  Automatically adapts to the number of channels and sampling rate of the consumer.

